Add functionality to ensure users gets and receives data from the API
Buyaki01/leaderboard_api pull request #2
Opened 2021-12-15 19:17 UTC by Buyaki01

- Create a new game with the name of your choice by using the API
- Implement the "Refresh" button (receiving data from the API and parsing the JSON).
- Implement the form "Submit" button (sending data to the API).
- Use async and await JavaScript features to consume the API.

2021-12-15 19:48 UTC, ZeenatLawal requested changes
Hi @Buyaki01, 

Great job so far!:clap: :clap:
## To Highlight 🎊 🎊 
- GitHub flow is followed. ✔️
- PR has a title and summary. ✔️

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-15 19:48 UTC, ZeenatLawal commented on src/index.js
>    const tableRow = document.createElement('tr');
- [ ] Kindly make use of arrow functions instead of the function keyword to follow ES6 best practices.

2021-12-15 19:48 UTC, ZeenatLawal commented on src/index.js
> +  // Get scores data
- [ ] Kindly make use of arrow functions instead of the function keyword to follow ES6 best practices.

2021-12-15 19:48 UTC, ZeenatLawal commented on src/index.js
> +  fetch(requestURL, {
- [ ] Kindly make use of arrow functions instead of the function keyword to follow ES6 best practices.

2021-12-15 19:48 UTC, ZeenatLawal commented on src/index.js
> +  allScores.forEach((score) => scoreElement(score.user, score.score));
- [ ] Kindly make use of arrow functions instead of the function keyword to follow ES6 best practices.

2021-12-15 19:48 UTC, ZeenatLawal commented on src/index.js
> +  fetch(requestURL, {
- [ ] Kindly make use of arrow functions instead of the function keyword to follow ES6 best practices.

2021-12-16 20:10 UTC, leolpaz approved these changes
Hi @Buyaki01 , 

Your project is complete!
Congratulations! 🎉🎉 

To highlight:

-  Congratulations on implementing the suggestions required by the first reviewer

Now there is nothing left to do but to merge it! 🏆 

![](https://media2.giphy.com/media/l3fQc3aCV0HqpzWcU/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 20:13 UTC, merged